Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Exclude:
    - lib/lois/cli.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
